# coding=utf-8
import requests
data = [
  {
    "number": 500,
    "country_code": "GB",
    "name": "Nike Store Kings Road",
    "city": "London",
    "address_1": "33 King's Rd",
    "address_2": "",
    "state": "Greater London",
    "postal_code": "SW3 4LX",
    "phone_number": "00 44 2072 599960",
    "email": "test@test.com"
  },
  {
    "number": 501,
    "country_code": "GB",
    "name": "Nike LAB 1948LDN London Store",
    "city": "London",
    "address_1": "477-478 Batemen's Row",
    "address_2": "",
    "state": "Greater London",
    "postal_code": "EC2 3HH",
    "phone_number": "00 44 0 207 729 7688",
    "email": "test@test.com"
  },
  {
    "number": 531,
    "country_code": "GB",
    "name": "Nike Town London",
    "city": "London",
    "address_1": "236 Oxford Street",
    "address_2": "",
    "state": "Greater London",
    "postal_code": "W1C 1DE",
    "phone_number": "00 44 207 612 0800",
    "email": "test@test.com"
  },
  {
    "number": 532,
    "country_code": "GB",
    "name": "Nike Store Glasgow",
    "city": "Glasgow",
    "address_1": "20-26 Buchanan Street",
    "address_2": "",
    "state": "GLG",
    "postal_code": "G1 3LB",
    "phone_number": "00 44 1412 211736",
    "email": "test@test.com"
  },
  {
    "number": 805,
    "country_code": "GB",
    "name": "Nike Store Liverpool",
    "city": "Liverpool",
    "address_1": "24 Paradise Street",
    "address_2": "",
    "state": "Merseyside",
    "postal_code": "L1 8JF",
    "phone_number": "00 44 1517 090768",
    "email": "test@test.com"
  },
  {
    "number": 806,
    "country_code": "GB",
    "name": "Nike Store London Westfield",
    "city": "London",
    "address_1": "Ariel Way",
    "address_2": "",
    "state": "Greater London",
    "postal_code": "W12 7GF",
    "phone_number": "00 44 208 749 3725",
    "email": "test@test.com"
  },
  {
    "number": 811,
    "country_code": "GB",
    "name": "Nike Store BlueWater",
    "city": "London",
    "address_1": "Upper Guildhall",
    "address_2": "U118",
    "state": "Greater London",
    "postal_code": "DA9 9SS",
    "phone_number": "00044 20 3479 5945",
    "email": "test@test.com"
  },
  {
    "number": 814,
    "country_code": "GB",
    "name": "Nike Store Covent Garden",
    "city": "London",
    "address_1": "14-16 Neal Street",
    "address_2": "",
    "state": "Greater London",
    "postal_code": "WC2H 9LY",
    "phone_number": "0039 02 8901 1231",
    "email": "test@test.com"
  },
  {
    "number": 817,
    "country_code": "GB",
    "name": "Nike Store Cardiff",
    "city": "Cardiff",
    "address_1": "Dewi Sant",
    "address_2": "Unit 80-82 Upper Level",
    "state": "Cardiff",
    "postal_code": "CF10 2EL",
    "phone_number": "00972 4695 1503",
    "email": "test@test.com"
  },
  {
    "number": 504,
    "country_code": "GB",
    "name": "Nike Factory Store Cheshire Oaks",
    "city": "Cheshire Oaks",
    "address_1": "31 Kinsey Road",
    "address_2": "",
    "state": "Cheshire West and Chester",
    "postal_code": "CH65 9JJ",
    "phone_number": "0033 1 60 29 71 73",
    "email": "test@test.com"
  },
  {
    "number": 510,
    "country_code": "GB",
    "name": "Nike Factory Store Swindon",
    "city": "Swindon",
    "address_1": "Kemble Drive",
    "address_2": "Unit 69-72",
    "state": "Wiltshire",
    "postal_code": "SN22DZ",
    "phone_number": "0039 06 4778 6860",
    "email": "test@test.com"
  },
  {
    "number": 523,
    "country_code": "GB",
    "name": "Nike Factory Store Tillicoultry",
    "city": "Tillicoultry",
    "address_1": "Moss road",
    "address_2": "Unit 28",
    "state": "Clackmannanshire",
    "postal_code": "FK13 6HQ",
    "phone_number": "0035 1 912 284 724",
    "email": "test@test.com"
  },
  {
    "number": 525,
    "country_code": "GB",
    "name": "Nike Factory Store Braintree",
    "city": "Essex",
    "address_1": "Charter Way",
    "address_2": "Unit 36 Freeport Village",
    "state": "Essex",
    "postal_code": "CM77 8YH",
    "phone_number": "0031 20 528 6330",
    "email": "test@test.com"
  },
  {
    "number": 526,
    "country_code": "GB",
    "name": "Nike Factory Store Castleford",
    "city": "Castleford",
    "address_1": "Carrwood Road",
    "address_2": "",
    "state": "West Yorkshire",
    "postal_code": "WF10 4PS",
    "phone_number": "0033(0)145774936",
    "email": "test@test.com"
  },
  {
    "number": 529,
    "country_code": "GB",
    "name": "Nike Factory Store Ashford",
    "city": "Ashford",
    "address_1": "65-69 Kimberley Way",
    "address_2": "",
    "state": "Kent",
    "postal_code": "TN24 0SD",
    "phone_number": "007 (863) 204 05 89",
    "email": "test@test.com"
  },
  {
    "number": 542,
    "country_code": "GB",
    "name": "Nike Factory Store Portsmouth",
    "city": "Portsmouth",
    "address_1": "Gunwharf Quays",
    "address_2": "Portsmouth PO1 3TA",
    "state": "Hampshire",
    "postal_code": "PO1 3TA",
    "phone_number": "00 44 2392 752822",
    "email": "test@test.com"
  },
  {
    "number": 553,
    "country_code": "GB",
    "name": "Nike Factory Store Royal Quays",
    "city": "North Shields",
    "address_1": "Royal Quays Shopping Outlet",
    "address_2": "Unit 19",
    "state": "North Tyneside",
    "postal_code": "NE296DW",
    "phone_number": "00 44 1912 708796",
    "email": "test@test.com"
  },
  {
    "number": 585,
    "country_code": "GB",
    "name": "Nike Factory Store Junction 1",
    "city": "Antrim",
    "address_1": "Junction 1 Retail Park",
    "address_2": "Ballymena Road",
    "state": "Antrim",
    "postal_code": "BT41 4LL",
    "phone_number": "00 44 2894 467757",
    "email": "test@test.com"
  },
  {
    "number": 606,
    "country_code": "GB",
    "name": "Nike Factory Store Bridgewater",
    "city": "Down",
    "address_1": "Bridgewater Park",
    "address_2": "Unit 41,",
    "state": "BNB",
    "postal_code": "BT32 4GJ",
    "phone_number": "00 44 2840 662200",
    "email": "test@test.com"
  },
  {
    "number": 614,
    "country_code": "GB",
    "name": "Nike Factory Store Hatfield",
    "city": "Hatfield",
    "address_1": "Comet Way",
    "address_2": "Unit 62",
    "state": "Hertfordshire",
    "postal_code": "AL10 0XR",
    "phone_number": "00 44 1707 260450",
    "email": "test@test.com"
  },
  {
    "number": 622,
    "country_code": "GB",
    "name": "Nike Factory Store York",
    "city": "York",
    "address_1": "St Nicholas Ave",
    "address_2": "Unit 57",
    "state": "York",
    "postal_code": "YO19 4TA",
    "phone_number": "00 44 1904 631179",
    "email": "test@test.com"
  },
  {
    "number": 623,
    "country_code": "GB",
    "name": "Nike Factory Store Livingston",
    "city": "Livingston",
    "address_1": "Livingston designer outlet",
    "address_2": "unit 87-90",
    "state": "West Lothian",
    "postal_code": "EH54 6QX",
    "phone_number": "00 44 1506 466645",
    "email": "test@test.com"
  },
  {
    "number": 631,
    "country_code": "GB",
    "name": "Nike Factory Store Gloucester Quays",
    "city": "Gloucester",
    "address_1": "St Ann Way",
    "address_2": "Unit 10-12",
    "state": "Gloucestershire",
    "postal_code": "GL1 5SH",
    "phone_number": "00 44 1452 526633",
    "email": "test@test.com"
  },
  {
    "number": 633,
    "country_code": "GB",
    "name": "Nike Factory Store Mansfield",
    "city": "South Normanton",
    "address_1": "Mansfield Road",
    "address_2": "Unit 39",
    "state": "Derbyshire",
    "postal_code": "DE55 2JW",
    "phone_number": "00 441773 511868",
    "email": "test@test.com"
  },
  {
    "number": 634,
    "country_code": "GB",
    "name": "Nike Factory Store Gretna Gateway Opening",
    "city": "Gretna",
    "address_1": "Glasgow Road",
    "address_2": "Unit 22",
    "state": "Dumfries and Galloway",
    "postal_code": "DG16 5GG",
    "phone_number": "00 44 1461 337601",
    "email": "test@test.com"
  },
  {
    "number": 641,
    "country_code": "GB",
    "name": "Nike Factory Store Atlantic Village",
    "city": "Bideford",
    "address_1": "23, Atlantic Village",
    "address_2": "Clovelly Road",
    "state": "Devon",
    "postal_code": "EX39 3QU",
    "phone_number": "00 44 1237 471 364",
    "email": "test@test.com"
  },
  {
    "number": 665,
    "country_code": "GB",
    "name": "Nike Factory Store West Thurrock",
    "city": "Thurrock",
    "address_1": "1A, Thurrock Shopping Park",
    "address_2": "Weston Avenue",
    "state": "Essex",
    "postal_code": "RM20 3LP",
    "phone_number": "00 44 1708 864075",
    "email": "test@test.com"
  },
  {
    "number": 800,
    "country_code": "GB",
    "name": "Nike Factory Store Birmingham One Stop",
    "city": "Birmingham",
    "address_1": "2 Walsall Road",
    "address_2": "",
    "state": "Birmingham",
    "postal_code": "B42 1AA",
    "phone_number": "00 44 1213 567195",
    "email": "test@test.com"
  },
  {
    "number": 802,
    "country_code": "GB",
    "name": "Nike Factory Store Durham Arnison",
    "city": "Durham",
    "address_1": "Abbey Rd",
    "address_2": "Unit J",
    "state": "Durham County",
    "postal_code": "DG1 5GB",
    "phone_number": "00 44 191 3867389",
    "email": "test@test.com"
  },
  {
    "number": 818,
    "country_code": "GB",
    "name": "Nike Factory Store Wembley",
    "city": "London",
    "address_1": "London Designer Outlet",
    "address_2": "42-45 Wembley Boulevard",
    "state": "Greater London",
    "postal_code": "HA9 0TG",
    "phone_number": "00 44 2089 031696",
    "email": "test@test.com"
  },
  {
    "number": 819,
    "country_code": "GB",
    "name": "Nike Factory Store Manchester Fort",
    "city": "Manchester",
    "address_1": "Cheetham Hill Road",
    "address_2": "Unit 23",
    "state": "Gt Man",
    "postal_code": "M88EP",
    "phone_number": "00 44 1618 326203",
    "email": "test@test.com"
  },
  {
    "number": 820,
    "country_code": "GB",
    "name": "Nike Factory Store Chester Broughton",
    "city": "Chester",
    "address_1": "Chester Road",
    "address_2": "Unit 3b",
    "state": "FLN",
    "postal_code": "CH4 0DE",
    "phone_number": "00 44 0124 4539625",
    "email": "test@test.com"
  },
  {
    "number": 821,
    "country_code": "GB",
    "name": "Nike Factory Store Glasgow StrathKelvin",
    "city": "Glasgow",
    "address_1": "Crosshill Rd",
    "address_2": "Unit 8",
    "state": "Glasgow",
    "postal_code": "G64 2TS",
    "phone_number": "00 44 1417 722034",
    "email": "test@test.com"
  },
  {
    "number": 822,
    "country_code": "GB",
    "name": "Nike Factory Store Norwich",
    "city": "Norwich",
    "address_1": "Albion Way",
    "address_2": "Unit 1",
    "state": "NFK",
    "postal_code": "NR1 1WR",
    "phone_number": "00 44 1603 665555",
    "email": "test@test.com"
  },
  {
    "number": 897,
    "country_code": "GB",
    "name": "Nike Factory Store Rotherham",
    "city": "Rotherham",
    "address_1": "Stadium Way",
    "address_2": "Unit 2A",
    "state": "South Yorkshire",
    "postal_code": "S60 1TG",
    "phone_number": "00 44 1709 780187",
    "email": "test@test.com"
  },
  {
    "number": "IT900",
    "country_code": "IT",
    "name": "Nike Factory Store Florence The Mall",
    "city": "Leccio Reggello",
    "address_1": "Via Europa, 8",
    "address_2": "",
    "state": "",
    "postal_code": 50066,
    "phone_number": "00 39 0558 657140",
    "email": "test@test.com"
  },
  {
    "number": 959,
    "country_code": "GB",
    "name": "Nike Factory Store East Kilbride",
    "city": "Glasgow",
    "address_1": "East Kilbride",
    "address_2": "Unit 7B",
    "state": "Glasgow",
    "postal_code": "G747UN",
    "phone_number": "0044 20 3479 5945",
    "email": "test@test.com"
  },
  {
    "number": 962,
    "country_code": "GB",
    "name": "Nike Factory Store Edinburgh Loanhead",
    "city": "Midlothian",
    "address_1": "13 Straiton Mains",
    "address_2": "Unit 1A",
    "state": "Midlothian",
    "postal_code": "EH20 9QY",
    "phone_number": "0033 1 82 97 05 89",
    "email": "test@test.com"
  },
  {
    "number": 972,
    "country_code": "GB",
    "name": "Nike Factory Store London Taplow",
    "city": "Maidenhead",
    "address_1": "Bath Road",
    "address_2": "Taplow Shopping Park, Unit 3, Bishop entre",
    "state": "Buckinghamshire",
    "postal_code": "SL60NX",
    "phone_number": "0044 1628 669961",
    "email": "test@test.com"
  },
  {
    "number": 974,
    "country_code": "GB",
    "name": "Nike Factory Store London Enfield",
    "city": "London",
    "address_1": "Crown Road",
    "address_2": "Unit 2",
    "state": "Greater London",
    "postal_code": "EN1 1TH",
    "phone_number": "0044 2083 621810",
    "email": "test@test.com"
  },
  {
    "number": 983,
    "country_code": "GB",
    "name": "Nike Factory Store Leeds Crown Point",
    "city": "Leeds",
    "address_1": "4, Crown Point Shopping Center",
    "address_2": "Junction Road",
    "state": "West Yorkshire",
    "postal_code": "LS10 1ET",
    "phone_number": "00 44 1132 439912",
    "email": "test@test.com"
  },
  {
    "number": 997,
    "country_code": "GB",
    "name": "Nike Factory Store Edinburgh",
    "city": "Edinburgh",
    "address_1": "South Groathill Avenue",
    "address_2": "Unit 2",
    "state": "Edinburgh",
    "postal_code": "EH4 2LN",
    "phone_number": "00 44 1313 325076",
    "email": "test@test.com"
  },
  {
    "number": 916,
    "country_code": "TR",
    "name": "Nike Factory Store Istanbul Venezia",
    "city": "Istanbul",
    "address_1": "Eski Edirne Asfalt",
    "address_2": "",
    "state": "",
    "postal_code": 34250,
    "phone_number": "0090 212 803 11 38",
    "email": "test@test.com"
  },
  {
    "number": 918,
    "country_code": "GB",
    "name": "Nike Factory Store Hackney",
    "city": "London",
    "address_1": "107-117 Morning Lane",
    "address_2": "",
    "state": "Greater London",
    "postal_code": "E9 6JL",
    "phone_number": "0041 619652500",
    "email": "test@test.com"
  },
  {
    "number": "GB2000",
    "country_code": "GB",
    "name": "Nike Factory Store Birmingham",
    "city": "Birmingham",
    "address_1": "Resorts World Unit 19",
    "address_2": "Pendigo Way",
    "state": "Birmingham",
    "postal_code": "B40 1PU",
    "phone_number": "0044 121 767 5680",
    "email": "test@test.com"
  },
  {
    "number": 608,
    "country_code": "GB",
    "name": "Nike Clearance Store Astle Park",
    "city": "Birmingham",
    "address_1": "Unit 5, Astle Outlet Park",
    "address_2": "",
    "state": "Birmingham",
    "postal_code": "B70 8NS",
    "phone_number": "0044 121 580 2981",
    "email": "test@test.com"
  },
  {
    "number": 642,
    "country_code": "GB",
    "name": "Nike Clearance Store Talke",
    "city": "Stoke-on-Trent",
    "address_1": "talke retail park",
    "address_2": "",
    "state": "Staffordshire",
    "postal_code": "ST71XD",
    "phone_number": "007 (863) 204 05 89",
    "email": "test@test.com"
  },
  {
    "number": 2026,
    "country_code": "GB",
    "name": "NIKE CENTRAL KING'S CROSS",
    "city": "London",
    "address_1": "2 Pancras Square",
    "address_2": "Zone B",
    "state": "Greater London",
    "postal_code": "N1C 4AG",
    "phone_number": "0044 20 3005 2805",
    "email": "test@test.com"
  },
  {
    "number": 657,
    "country_code": "TR",
    "name": "Nike Factory Store Bolu",
    "city": "Bolu",
    "address_1": "Otoyolu Elmalik Mevkii Highway outlet",
    "address_2": "",
    "state": "",
    "postal_code": "14100 Bolu",
    "phone_number": "00 90 3742 501707",
    "email": "test@test.com"
  },
  {
    "number": 671,
    "country_code": "TR",
    "name": "Nike Factory Store Ankara Nata Vega",
    "city": "Ankara",
    "address_1": "Ankara Nata Vega Outlet Center, Aksemseddin Mah. Dogukent Cad. No:213 1K138-2",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 3125 542636",
    "email": "test@test.com"
  },
  {
    "number": 672,
    "country_code": "TR",
    "name": "Nike Factory Store Izmir",
    "city": "Izmir",
    "address_1": "Optimum Outlet Ve Eglence Merkezi, Dokuz Eylul Mh., Akcay Cd No:101",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 2322 738100",
    "email": "test@test.com"
  },
  {
    "number": 682,
    "country_code": "HR",
    "name": "Nike Factory Store Split",
    "city": "Split",
    "address_1": "Svetog Lopolda Mandica 13",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 38 5214 90982",
    "email": "test@test.com"
  },
  {
    "number": 683,
    "country_code": "TR",
    "name": "Nike Factory Store Izmit Kocaeli",
    "city": "Izmit Kocaeli",
    "address_1": "Outlet Center Izmit, Eski Golcuk Yolu Uzeri. Unit A101",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 2623 351097",
    "email": "test@test.com"
  },
  {
    "number": 684,
    "country_code": "TR",
    "name": "Nike Factory Store Soke",
    "city": "Soke",
    "address_1": "Atatürk Mah., Aydın Yolu 216",
    "address_2": "",
    "state": "",
    "postal_code": "09207 Söke/Aydın",
    "phone_number": "00 90 2565 188824",
    "email": "test@test.com"
  },
  {
    "number": 685,
    "country_code": "PL",
    "name": "Nike Factory Store Szczecin",
    "city": "Szczecin",
    "address_1": "Outlet Park Szczecin, ul. Struga 42 , Unit A.L. - 0652",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 48 9181 06765",
    "email": "test@test.com"
  },
  {
    "number": 687,
    "country_code": "TR",
    "name": "Nike Factory Store Istanbul Deposit",
    "city": "Istanbul",
    "address_1": "Deposite Outlet Merkezi, A5-A6",
    "address_2": "",
    "state": "",
    "postal_code": "34490 Başakşehir/Istanbul",
    "phone_number": "00 90 2126 716068",
    "email": "test@test.com"
  },
  {
    "number": 660,
    "country_code": "RU",
    "name": "Nike Factory Store Savelosky",
    "city": "Moscow",
    "address_1": "Suschevsky val. 5 bld1,",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 4952 760571",
    "email": "test@test.com"
  },
  {
    "number": 667,
    "country_code": "RU",
    "name": "Nike Factory Store Ordzhonikidze",
    "city": "Moscow",
    "address_1": "Ordjonikidze str. 11 bld.1",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 4952 343158",
    "email": "test@test.com"
  },
  {
    "number": 675,
    "country_code": "GR",
    "name": "Nike Factory Store Xanthi",
    "city": "Xanthi",
    "address_1": "Flamingo Retail Park , Unit 4.2 , 4th km National Road",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 30 2541 066681",
    "email": "test@test.com"
  },
  {
    "number": 791,
    "country_code": "IL",
    "name": "Nike Factory Store Holon",
    "city": "Holon",
    "address_1": "38 Merkava",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 97 2035 625688",
    "email": "test@test.com"
  },
  {
    "number": 824,
    "country_code": "TR",
    "name": "Nike Factory Store Istanbul Pelikan",
    "city": "Istanbul",
    "address_1": "Pelican Mall Alisveris Merkezi ve Yasam Merkezi, universite Mahallesi Selvi Sok. No:25 E5 uzeri, Unit: 74-76",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 2124 502008",
    "email": "test@test.com"
  },
  {
    "number": 990,
    "country_code": "RU",
    "name": "Nike Factory Store Moscow Fashion House",
    "city": "Moscow",
    "address_1": "Moscow region. Solnechnogorsky district , Chernaya Gryaz' village., Torgovo-Promyshlennaya str. 6",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 4956 41302627",
    "email": "test@test.com"
  },
  {
    "number": 896,
    "country_code": "TR",
    "name": "Nike Factory Store Istanbul Olivium",
    "city": "Istanbul",
    "address_1": "Prof. Dr. Muammer Aksoy Cad no. 1/1",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 0212 4155531",
    "email": "test@test.com"
  },
  {
    "number": 898,
    "country_code": "SK",
    "name": "Nike Factory Store Bratislava",
    "city": "Bratislava",
    "address_1": "ONE Fashion Outlet, Voderady 440",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 42 1332 420002",
    "email": "test@test.com"
  },
  {
    "number": 904,
    "country_code": "TR",
    "name": "Nike Factory Store Istanbul Armonipark",
    "city": "Istanbul",
    "address_1": "ArmoniPark Outlet Center, Tevfik Bey Mahallesi. Halkali Caddesi No:132",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 2124 252051",
    "email": "test@test.com"
  },
  {
    "number": 654,
    "country_code": "RU",
    "name": "Nike Factory Store Novoslobodskaya",
    "city": "Moscow",
    "address_1": "Novoslobodskaya ulitsa 3",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 4959 261626",
    "email": "test@test.com"
  },
  {
    "number": 936,
    "country_code": "RU",
    "name": "Nike Factory Store Sokolniki",
    "city": "Moscow",
    "address_1": "Sokolnicheskaya sq.. 9 bld. 1",
    "address_2": "",
    "state": "",
    "postal_code": "127006 Moskva",
    "phone_number": "00 7 4952 760547",
    "email": "test@test.com"
  },
  {
    "number": 692,
    "country_code": "RU",
    "name": "Nike Factory Store Kazan Tsum",
    "city": "Kazan",
    "address_1": "Moskovskaya ulitsa 2",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 8435 260368",
    "email": "test@test.com"
  },
  {
    "number": 939,
    "country_code": "PL",
    "name": "Nike Factory Store Poznan",
    "city": "Lubon",
    "address_1": "Factory Poznan, ul. Debiecka 1",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 48 6165 23005",
    "email": "test@test.com"
  },
  {
    "number": 693,
    "country_code": "RU",
    "name": "Nike Factory Store Kazan XL",
    "city": "Kazan",
    "address_1": "Prospekt Khusaina, Yamasheva 97",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 8435 192978",
    "email": "test@test.com"
  },
  {
    "number": 679,
    "country_code": "RU",
    "name": "Nike Factory Store Yekaterinburg",
    "city": "Yekaterinburg",
    "address_1": "Karla Libknehta street 23B",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 3432 871689",
    "email": "test@test.com"
  },
  {
    "number": 945,
    "country_code": "IL",
    "name": "Nike Factory Store Krayot",
    "city": "Krayot",
    "address_1": "Sderot Hahistadrut 248",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 972 4638 6654",
    "email": "test@test.com"
  },
  {
    "number": 946,
    "country_code": "TR",
    "name": "Nike Factory Store Eskisehir",
    "city": "Eskisehir",
    "address_1": "NeoPlus Outlet ve Yasam Merkezi, camlica Mahallesi Gulperi Sokak No:1 Unit 121-124 Merkez / Tepebasi",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 2223 101120",
    "email": "test@test.com"
  },
  {
    "number": 948,
    "country_code": "TR",
    "name": "Nike Factory Store Antalya Beka",
    "city": "Antalya Beka",
    "address_1": "Yeşilbahçe, 07160 Muratpaşa/Antalya, Turkey",
    "address_2": "`",
    "state": "",
    "postal_code": "07160 Muratpaşa/Antalya",
    "phone_number": "00 90 2423 412041",
    "email": "test@test.com"
  },
  {
    "number": 949,
    "country_code": "TR",
    "name": "Nike Factory Store Tarsus",
    "city": "Tarsus",
    "address_1": "Fevzi Çakmak, Adana Blv, 33460 Tarsus/Mersin",
    "address_2": "",
    "state": "",
    "postal_code": "33460 Tarsus/Mersin",
    "phone_number": "00 90 3246 220113",
    "email": "test@test.com"
  },
  {
    "number": 985,
    "country_code": "TR",
    "name": "Nike Factory Store Viaport",
    "city": "Istanbul",
    "address_1": "Yenisehir Mahallesi Dedepasa Caddesi 19",
    "address_2": "ViaPort Outlet Alisveris Merkezi",
    "state": "",
    "postal_code": "34912 Pendik/İstanbul",
    "phone_number": "00 90 2166 961237",
    "email": "test@test.com"
  },
  {
    "number": 792,
    "country_code": "RU",
    "name": "Nike Factory Store Pulkovo St Petersburg",
    "city": "St Petersburg",
    "address_1": "Pulkovskoe shosse, 104",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "0049 34954 31510",
    "email": "test@test.com"
  },
  {
    "number": 989,
    "country_code": "RU",
    "name": "Nike Factory Store South Pole St Petersburg",
    "city": "St. Petersburg",
    "address_1": "Prazhskaya 48/50",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 8123 36887273",
    "email": "test@test.com"
  },
  {
    "number": 658,
    "country_code": "RU",
    "name": "Nike Factory Store Orion St Petersburg",
    "city": "St. Petersburg",
    "address_1": "Nevsky Prospect 35",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 7 8127 023273",
    "email": "test@test.com"
  },
  {
    "number": 993,
    "country_code": "TR",
    "name": "Nike Factory Store Ankara Forum",
    "city": "Ankara",
    "address_1": "Yozgat Bulvari 99",
    "address_2": "Ovacik Kecioren",
    "state": "",
    "postal_code": "Ankara 06280",
    "phone_number": "00 90 3125 780445",
    "email": "test@test.com"
  },
  {
    "number": 2014,
    "country_code": "TR",
    "name": "Nike Factory Store Konya Novada",
    "city": "Konya",
    "address_1": "Novada Outlet Konya, Sancak Mahallesi, Veysel Karani Caddesi, No:4, Unit B112-115, Selcuklu",
    "address_2": "",
    "state": "",
    "postal_code": "",
    "phone_number": "00 90 332 502 02 38",
    "email": "test@test.com"
  }
]
for i in data:
    r = requests.post('http://nike-uat.brickworksoftware.com/api/v3/admin/stores/?api_key=XXXXXXX', json=i)
    print r.text

